---
title: "Thesis2022_PlantFamilies"
author: "Amanda Hastings"
date: "2022-11-08"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Read in data 
ThesisDataRaw <- read.csv("HastingsA_MasterThesisData8.8.22.csv")
TerraData <- read.csv("HastingsA_TerraclimateMaster8.16.csv")
ThesisSeedlingsData <- read.csv("HastingsA_MasterSeedlingsData9.12.22.csv")

#Load libraries
library(tidyverse)
library(dplyr)
library(RColorBrewer)
library(emmeans)
library(multcomp)
library(multcompView)
library(ggthemes)
library(vegan)
library(ggvegan)
library(ggpubr)
library(viridis)
library(scales)
```

## Formatting raw thesis site data and seedlings data 

```{r}
#Filter to only wanted sites in ThesisData 
ThesisData <- ThesisDataRaw %>% 
  filter(!PlotID %in% c('LS11','HS02','HS12','HS13', 'LS01_MV','LS02_MV','HS01_MV'))

ThesisSeedlings <- ThesisSeedlingsData %>% 
  filter(!PlotID %in% c('LS11','HS02','HS12','HS13'))%>% 
  dplyr::select(!c(Fire_name, regen_radius, regenplot_size_m2, regenplot_size_ha))%>% 
  select_if(~!any(is.na(.)))

```

## Combining site data with seedlings data

```{r}
ThesisAll1 <- full_join(ThesisData, ThesisSeedlings, by= "PlotID") %>% 
  arrange(PlotID)%>% 
  mutate(forest_type = factor(forest_type))
```

## Add in plant family data frame 

```{r}
#Load plant family data 
families_data <- read.csv("HastingsA_FamilyCounts_11.7.22.csv")

families_data <- families_data %>% 
  mutate("percent_cover" = Count/127)

n_distinct(families_data$PlotID)
```


## Append burn severity and forest type to PlotID

```{r}
PlotCat <- ThesisAll1 %>% 
  dplyr::select(PlotID, burn_sev_category, forest_type)%>% 
  filter(!PlotID %in% "LS30")

#Append categories to PlotID in plant family dataframe 
families_data <- left_join(families_data, PlotCat, by = "PlotID")

#Summarize plant family cover by burn severity and forest type 
families_sumstats <- families_data %>%
  group_by(forest_type, burn_sev_category, Family) %>%
  mutate(forest_type = factor(
    forest_type,
    levels = c("Lower Montane", "Upper Montane","Subalpine")))%>%
  summarize(mean_percent_cover = mean(percent_cover)) %>%
  mutate(mean_percent_cover = replace(mean_percent_cover, mean_percent_cover == 0.0000, NA))%>% 
  na.omit()%>% 
  filter(mean_percent_cover > 0.01)
```

## Plant families by burn severity  

```{r}

#Plant family plot by burn severity 
PlantFamily_Burn <- ggplot(
  families_sumstats,
  aes(x = Family,
      y = mean_percent_cover, 
      fill = burn_sev_category)
) +
  geom_boxplot() + 
  # ylim(0, 0.6) +
  labs(x = "Plant Family",
       y = "Percent Cover",
       fill = "Burn Severity") +
  theme(legend.position = "bottom",
        legend.key.width = unit(1, "cm")) +
  theme_few()+
  scale_fill_manual(
    name = "Burn Severity",
    labels = c("High", "Low"), values=c("#bd0026","#fd8d3c"))+
  scale_y_continuous(labels = percent)+
  theme(axis.text.x = element_text(
    color = "black",
    size = 7,
    angle = 90
  ),
  axis.title.x = element_text(size = 11),
  axis.title.y = element_text(size = 11),
  axis.text.y = element_text(size = 8),
  legend.title = element_text(size = 9), 
  legend.text = element_text(size =9))
  # scale_x_discrete(labels = c("Forbs", "Graminoids", "Shrubs", "Seedlings"))+
  

PlantFamily_Burn

```

## Plant families by forest type 


```{r}

#Plant family plot by forest type  
PlantFamily_Forest <- ggplot(
  families_sumstats,
  aes(x = Family,
      y = mean_percent_cover, 
      fill = forest_type)
) +
  geom_boxplot() + 
  labs(x = "Plant Family",
       y = "Percent Cover",
       fill = "Forest Type") +
  theme(legend.position = "bottom",
        legend.key.width = unit(1, "cm")) +
  theme_few()+
  scale_fill_manual(
    name = "Forest Type",
    labels = c("Lower Montane", "Upper Montane", "Subalpine"), values=c("#9ebc00","#ffc107","#981679"))+
  theme(axis.text.x = element_text(
    color = "black",
    size = 7,
    angle = 90
  ),
  axis.title.x = element_text(size = 11),
  axis.title.y = element_text(size = 11),
  axis.text.y = element_text(size = 8),
  legend.title = element_text(size = 9), 
  legend.text = element_text(size =9)) + 
  # scale_x_discrete(labels = c("Forbs", "Graminoids", "Shrubs", "Seedlings"))+
  scale_y_continuous(labels = percent)

PlantFamily_Forest

```


## Plant families by forest type with facet wrap

```{r}
#Plant family plot by forest type facet 
PlantFamily_ForestFacet <- ggplot(
  families_sumstats,
  aes(x = Family,
      y = mean_percent_cover, 
      fill=forest_type)
) +
  geom_boxplot(alpha =0.95) +
  facet_wrap(~ forest_type, scales="free_x") +
  # ylim(0, 0.6) +
  # theme_classic() +
  labs(x = "Plant Family",
       y = "Percent Cover") +
  theme(legend.position = "bottom",
        legend.key.width = unit(1, "cm")) +
  theme_few()+
  scale_fill_manual(
    name = "Forest Type",
    labels = c("Lower Montane", "Upper Montane", "Subalpine"), values=c("#9ebc00","#ffc107","#981679"))+
  theme(axis.text.x = element_text(
    color = "black",
    size = 7,
    angle = 90,
    vjust = 0.25
  ),
  axis.title.x = element_text(size = 11),
  axis.title.y = element_text(size = 11),
  axis.text.y = element_text(size = 8),
  legend.title = element_text(size = 9), 
  legend.text = element_text(size =9)) + 
  # scale_x_discrete(labels = c("Forbs", "Graminoids", "Shrubs", "Seedlings"))+
  scale_y_continuous(labels = percent)

PlantFamily_ForestFacet

```

## Separating by forest type 

```{r}

families_lowermontane <- families_sumstats %>% 
  filter(forest_type == "Lower Montane")


families_uppermontane <- families_sumstats %>% 
  filter(forest_type == "Upper Montane")


families_subalpine <- families_sumstats %>% 
  filter(forest_type == "Subalpine")
```


```{r}
#Plant family plot by forest type facet 
Subalpine_families <- ggplot(
  families_subalpine,
  aes(x = Family,
      y = mean_percent_cover)
) +
  geom_boxplot() +
  labs(x = "Plant Family",
       y = "Percent Cover") +
  theme(legend.position = "bottom",
        legend.key.width = unit(1, "cm")) +
  theme_few()+
  # scale_fill_manual(
  #   name = "Burn Severity",
  #   labels = c("High", "Low"), values=c("#bd0026","#fd8d3c"))+
  theme(axis.text.x = element_text(
    color = "black",
    size = 7,
    angle = 90,
    vjust = .8,
    hjust = .8
  ),
  axis.title.x = element_text(size = 11),
  axis.title.y = element_text(size = 11),
  axis.text.y = element_text(size = 8),
  legend.title = element_text(size = 9), 
  legend.text = element_text(size =9)) + 
  # scale_x_discrete(labels = c("Forbs", "Graminoids", "Shrubs", "Seedlings"))+
  scale_y_continuous(labels = percent)

Subalpine_families
```



```{r}
#Plant family plot by forest type facet 
Uppermontane_families <- ggplot(
  families_uppermontane,
  aes(x = Family,
      y = mean_percent_cover)
) +
  geom_boxplot() +
  labs(x = "Plant Family",
       y = "Percent Cover") +
  theme(legend.position = "bottom",
        legend.key.width = unit(1, "cm")) +
  theme_few()+
  # scale_fill_manual(
  #   name = "Burn Severity",
  #   labels = c("High", "Low"), values=c("#bd0026","#fd8d3c"))+
  theme(axis.text.x = element_text(
    color = "black",
    size = 7,
    angle = 90,
    vjust = .8,
    hjust = .8
  ),
  axis.title.x = element_text(size = 11),
  axis.title.y = element_text(size = 11),
  axis.text.y = element_text(size = 8),
  legend.title = element_text(size = 9), 
  legend.text = element_text(size =9)) + 
  # scale_x_discrete(labels = c("Forbs", "Graminoids", "Shrubs", "Seedlings"))+
  scale_y_continuous(labels = percent)

Uppermontane_families
```



```{r}
#Plant family plot by forest type facet 
Lowermontane_families <- ggplot(
  families_lowermontane,
  aes(x = Family,
      y = mean_percent_cover)
) +
  geom_boxplot() +
  labs(x = "Plant Family",
       y = "Percent Cover") +
  theme(legend.position = "bottom",
        legend.key.width = unit(1, "cm")) +
  theme_few()+
  # scale_fill_manual(
  #   name = "Burn Severity",
  #   labels = c("High", "Low"), values=c("#bd0026","#fd8d3c"))+
  theme(axis.text.x = element_text(
    color = "black",
    size = 7,
    angle = 90,
    vjust = .8,
    hjust = .8
  ),
  axis.title.x = element_text(size = 11),
  axis.title.y = element_text(size = 11),
  axis.text.y = element_text(size = 8),
  legend.title = element_text(size = 9), 
  legend.text = element_text(size =9)) + 
  # scale_x_discrete(labels = c("Forbs", "Graminoids", "Shrubs", "Seedlings"))+
  scale_y_continuous(labels = percent)

Lowermontane_families
```

## Plant families analyses 

```{r}
#Summarize plant family cover by burn severity and forest type 
families_sumstats2 <- families_data %>%
  group_by(forest_type, burn_sev_category, Family) %>%
  mutate(forest_type = factor(
    forest_type,
    levels = c("Lower Montane", "Upper Montane","Subalpine")))%>%
  summarize(mean_percent_cover = mean(percent_cover)) %>%
  mutate(mean_percent_cover = replace(mean_percent_cover, mean_percent_cover == 0.0000, NA))%>% 
  na.omit()

hist(families_sumstats2$mean_percent_cover)
hist(sqrt(families_sumstats2$mean_percent_cover))
```


```{r}
#
LMFamilies <- lm(sqrt(mean_percent_cover) ~ Family, data = families_sumstats2)
anova(LMFamilies)
par(mfrow = c(1, 2))
plot(LMFamilies, which = 1:2)
```


```{r}
emoutFamilies <- emmeans(LMFamilies, ~ Family)
emoutFamilies
pairs(emoutFamilies)
cld(emoutFamilies)
```

## NMDS plant families 

```{r}
#Data frame with family counts, pivot wider
families_NMDS <- families_data %>% 
  dplyr::select(PlotID, forest_type, burn_sev_category, Family, Count) %>% 
  filter(!Count ==0)%>% 
  na.omit()%>% 
  pivot_wider(names_from = Family, values_from = Count)

families_NMDS[is.na(families_NMDS)] <- 0

#standardize by hellinger method 
families_NMDS_matrix <- families_NMDS %>% 
  dplyr:: select(-forest_type, -burn_sev_category)%>%
  remove_rownames %>% 
  column_to_rownames(var="PlotID")%>% 
  decostand(., method='hellinger')
```




